Add an applicability statement
anima-wg/anima-brski-prm pull request #9
Opened 2021-11-24 11:56 UTC by elear

I think this is the text we discussed, and can do so again tomorrow.

2021-11-24 11:58 UTC, elear commented
Fixes #10

2021-11-24 14:32 UTC, stfries requested changes
Proposal to delete the last sentence. As BRSKI-PRM addresses the case in which the pledge is not the initiator, it would be contrary to use it as fallback here. A solution in this case may be that the pledge provides a (physically or other) wakeup function.

2021-11-24 17:51 UTC, mcr requested changes
I made two corrections: pledge-agent to registrar-agent. I can't recall if we are including the - or not.
In general, when I read about applicability, I'd rather that it had more positive hint.
I.e. "use this when X,Y,Z is true", while this text tells me to not use it when not-Q.

2021-11-24 17:51 UTC, mcr commented on draft-ietf-anima-brski-prm.md
> +communicate with the pledge agent.  This may not be possible in
```suggestion
communicate with the registrar-agent.  
This may not be possible in
```

2021-11-24 17:51 UTC, mcr commented on draft-ietf-anima-brski-prm.md
> +time, and the pledge agent is similarly presumed to be unavailable for
```suggestion
time, and the registrar-agent is similarly presumed to be unavailable for
```

2021-11-25 07:02 UTC, merged

2021-11-25 08:09 UTC, stfries commented
I accepted the proposal and changed the heading from Applicability to Limitations. As Michael wrote, the statements were rather directed towards examples, in which the approach does not work. I also deleted the last sentence, referring to BRSKI as this may not be an option for the pledge as server.


I made two corrections: pledge-agent to registrar-agent. I can't recall if we are including the - or not.

[stf] always with ”-“

In general, when I read about applicability, I'd rather that it had more positive hint.
I.e. "use this when X,Y,Z is true", while this text tells me to not use it when not-Q.

[stf] yes, changed to limitations.

________________________________

In draft-ietf-anima-brski-prm.md<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanima-wg%2Fanima-brski-prm%2Fpull%2F9%23discussion_r756311375&data=04%7C01%7Csteffen.fries%40siemens.com%7Cac6e785043a04148a88e08d9af731f39%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637733731243507731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P8vlgW56YroF1xvmYYucjB1rAT%2BsukIu%2BBnacf9l5Lg%3D&reserved=0>:

> @@ -211,6 +211,18 @@ The registration authority (RA) performing the authorization of a certificate re



 CAs may also demand higher security in the registration procedures. Especially the CA/Browser forum currently increases the security requirements in the certificate issuance procedures for publicly trusted certificates.



 There may be the situation in which the target domain does not offer enough security to operate a RA/CA and therefore this service is transferred to a backend that offers a higher level of operational security.







+## Applicability



+



+The mechanisms in this draft presume the availability of the pledge to



+communicate with the pledge agent.  This may not be possible in


⬇️ Suggested change

-communicate with the pledge agent.  This may not be possible in



+communicate with the registrar-agent.



+This may not be possible in



________________________________

In draft-ietf-anima-brski-prm.md<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanima-wg%2Fanima-brski-prm%2Fpull%2F9%23discussion_r756312010&data=04%7C01%7Csteffen.fries%40siemens.com%7Cac6e785043a04148a88e08d9af731f39%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637733731243507731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zARrcqapi%2FGhVu%2BimY0DVGqh%2BYIFZEWkwY0ZtnKJeDY%3D&reserved=0>:

> @@ -211,6 +211,18 @@ The registration authority (RA) performing the authorization of a certificate re



 CAs may also demand higher security in the registration procedures. Especially the CA/Browser forum currently increases the security requirements in the certificate issuance procedures for publicly trusted certificates.



 There may be the situation in which the target domain does not offer enough security to operate a RA/CA and therefore this service is transferred to a backend that offers a higher level of operational security.







+## Applicability



+



+The mechanisms in this draft presume the availability of the pledge to



+communicate with the pledge agent.  This may not be possible in



+constrained environments where, in particular, power must be



+conserved.  In these situations, it is anticipated that the



+transceiver will be powered down most of the time.  This presents a



+rendezvous problem: the pledge is unavailable for certain periods of



+time, and the pledge agent is similarly presumed to be unavailable for


⬇️ Suggested change

-time, and the pledge agent is similarly presumed to be unavailable for



+time, and the registrar-agent is similarly presumed to be unavailable for



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanima-wg%2Fanima-brski-prm%2Fpull%2F9%23pullrequestreview-815229768&data=04%7C01%7Csteffen.fries%40siemens.com%7Cac6e785043a04148a88e08d9af731f39%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637733731243507731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GaEiA0k7IZcTOg4z917vhM6EZK6%2B2GL6JQCR%2Fdvn7b0%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJEUR5LXALG7QQDE3RUQPBDUNUQ4DANCNFSM5IV4AHYQ&data=04%7C01%7Csteffen.fries%40siemens.com%7Cac6e785043a04148a88e08d9af731f39%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637733731243517688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sNcHiac%2BgmJOyTaVZdpc4lFDRdAmqvi8BpDx4ZMtEX8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csteffen.fries%40siemens.com%7Cac6e785043a04148a88e08d9af731f39%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637733731243517688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Tih535VnOESIO30Hln4bBiiBAKThCNKfJTA2AP6Snf4%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csteffen.fries%40siemens.com%7Cac6e785043a04148a88e08d9af731f39%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637733731243527641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ALjXt3RPyHpKizn00TOIlQ4lKgNkRBkBy8als%2FiB6Ao%3D&reserved=0>.